import { loadState, saveState, resetState, cloneState } from "./storage.js";
import { pushProgress, testConnection } from "./api.js";

let state=loadState(), route='home', quizSession=null, currentExplore=null;
const app=document.getElementById('app'), modal=document.getElementById('modal'), modalBody=document.getElementById('modalBody'), modalTitle=document.getElementById('modalTitle');

const moduleInfo={
 concept:{title:'Kenali Bilangan Rasional',badge:'Penjelajah Rasional',icon:'🧭'},
 conversion:{title:'Pecahan, Desimal, dan Persen',badge:'Ahli Konversi',icon:'🔄'},
 comparison:{title:'Membandingkan & Mengurutkan',badge:'Sang Pembanding',icon:'⚖️'}
};
const moduleOrder=Object.keys(moduleInfo);

function fraction(n,d,size=''){return `<span class="fraction ${size}"><span class="numerator">${n}</span><span class="fraction-line"></span><span class="denominator">${d}</span></span>`}
function fmtText(t=''){return String(t).replace(/\[\[(-?\d+)\/(\d+)\]\]/g,(_,n,d)=>fraction(n,d)).replace(/\n/g,'<br>')}
function multiplier(v){return `<span class="multiplier">× <span class="mini-frac"><span>${v}</span><span class="mini-line"></span><span>${v}</span></span></span>`}
function grid100Html(fill=0){return Array.from({length:100},(_,i)=>`<div class="cell100 ${i<fill?'active':''}" data-i="${i}"></div>`).join('')}
function quarterBoard(fill=0){return `<div class="quarter-board" id="quarterBoard">${[0,1,2,3].map(i=>`<div class="quarter ${i<fill?'q'+(i+1):'outline'}">${i<fill?'¼':''}</div>`).join('')}</div>`}
function wholeBar(parts,filled,label){return `<div class="picture-card"><div class="whole-label">${label}</div><div class="whole-bar" style="--parts:${parts}">${Array.from({length:parts},(_,i)=>`<div class="whole-part ${i<filled?'filled':''}"></div>`).join('')}</div><small>1 penuh = ${parts} bagian sama besar</small></div>`}

const exploreMap={
 integer3:{title:'Bilangan bulat menjadi rasional',stages:[
  {kind:'html',html:`<div class="math-stage"><p>Bilangan <b>3</b> adalah bilangan bulat.</p><div class="math-box">3</div></div>`},
  {kind:'html',html:`<div class="math-stage"><p>Setiap bilangan bulat dapat ditulis dengan penyebut 1.</p><div class="math-box">${fraction(3,1,'big')}</div></div>`},
  {kind:'html',html:`<div class="math-row"><div class="math-box">3</div><span class="math-symbol">=</span><div class="math-box">${fraction(3,1,'big')}</div></div><div class="hint">Karena dapat ditulis sebagai a/b dengan b ≠ 0, maka 3 adalah bilangan rasional.</div>`}
 ]},
 decimal05:{title:'0,5 menjadi pecahan',stages:[
  {kind:'html',html:`<div class="math-stage"><p>0,5 dibaca lima per sepuluh.</p><div class="math-box">0,5</div><div class="math-symbol">↓</div><div class="math-box">${fraction(5,10,'big')}</div></div>`},
  {kind:'tenths',fill:5,label:'Lima dari sepuluh bagian diwarnai.'},
  {kind:'html',html:`<div class="math-row"><div class="math-box">${fraction(5,10,'big')}</div><span class="math-symbol">=</span><div class="math-box">${fraction(1,2,'big')}</div></div>`}
 ]},
 decimal025:{title:'0,25 menjadi 1/4',stages:[
  {kind:'html',html:`<div class="math-stage"><p>Dua angka di belakang koma menggunakan penyebut 100.</p><div class="math-box">0,25</div><div class="math-symbol">↓</div><div class="math-box">${fraction(25,100,'big')}</div></div>`},
  {kind:'hundred-to-quarter',fill:25,quarters:1,label:`${fraction(25,100)} berarti 25 dari 100 kotak.`},
  {kind:'html',html:`<div class="math-row"><div class="math-box">${fraction(25,100,'big')}</div><span class="math-symbol">=</span><div class="math-box">${fraction(1,4,'big')}</div></div><div class="hint">100 kotak dikelompokkan menjadi 4 kelompok sama besar. Setiap kelompok berisi 25 kotak.</div>`}
 ]},
 percent75:{title:'75% menjadi 3/4',stages:[
  {kind:'html',html:`<div class="math-stage"><p>Persen berarti per seratus.</p><div class="math-box">75%</div><div class="math-symbol">↓</div><div class="math-box">${fraction(75,100,'big')}</div></div>`},
  {kind:'hundred-to-quarter',fill:75,quarters:3,label:'75 dari 100 kotak diwarnai. Setiap 25 kotak membentuk satu kelompok seperempat.'},
  {kind:'html',html:`<div class="math-row"><div class="math-box">${fraction(75,100,'big')}</div><span class="math-symbol">=</span><div class="math-box">${fraction(3,4,'big')}</div><span class="math-symbol">=</span><div class="math-box">0,75</div></div>`}
 ]},
 fraction34:{title:'3/4 menjadi desimal',stages:[
  {kind:'html',html:`<div class="math-stage"><p>Mulai dari pecahan biasa.</p><div class="math-box">${fraction(3,4,'big')}</div></div>`},
  {kind:'html',html:`<p class="center">Perkalian pembilang dan penyebut ditampilkan langsung di sebelah pecahan.</p><div class="math-row"><div class="math-box">${fraction(3,4,'big')}</div>${multiplier(25)}<span class="math-symbol">=</span><div class="math-box">${fraction(75,100,'big')}</div></div>`},
  {kind:'hundred-to-quarter',fill:75,quarters:3,label:`${fraction(75,100)} divisualisasikan sebagai 75 dari 100 kotak, lalu dikelompokkan menjadi 3 dari 4 bagian.`},
  {kind:'html',html:`<div class="math-row"><div class="math-box">${fraction(3,4,'big')}</div><span class="math-symbol">=</span><div class="math-box">0,75</div></div>`}
 ]},
 negative125:{title:'−1,25 menjadi pecahan rasional',stages:[
  {kind:'html',html:`<div class="math-stage"><p>Dua angka di belakang koma berarti penyebut 100.</p><div class="math-box">−1,25</div><div class="math-symbol">↓</div><div class="math-box">${fraction(-125,100,'big')}</div></div>`},
  {kind:'html',html:`<div class="math-row"><div class="math-box">${fraction(-125,100,'big')}</div><span class="math-symbol">=</span><div class="math-box">${fraction(-5,4,'big')}</div></div>`}
 ]}
};

const conversionCards={
 conv06:{title:'0,6 → pecahan',stages:[
  {kind:'html',html:`<div class="math-stage"><p>Satu angka di belakang koma memakai penyebut 10.</p><div class="math-box">0,6</div><div class="math-symbol">↓</div><div class="math-box">${fraction(6,10,'big')}</div></div>`},
  {kind:'tenths',fill:6,label:'Enam dari sepuluh bagian diwarnai.'},
  {kind:'html',html:`<div class="math-row"><div class="math-box">${fraction(6,10,'big')}</div><span class="math-symbol">=</span><div class="math-box">${fraction(3,5,'big')}</div></div>`}
 ]},
 conv035:{title:'0,35 → pecahan dan persen',stages:[
  {kind:'html',html:`<div class="math-stage"><p>Dua angka di belakang koma memakai penyebut 100.</p><div class="math-box">0,35</div><div class="math-symbol">↓</div><div class="math-box">${fraction(35,100,'big')}</div></div>`},
  {kind:'hundred',fill:35,label:'35 dari 100 kotak diwarnai.'},
  {kind:'html',html:`<div class="math-row"><div class="math-box">0,35</div><span class="math-symbol">=</span><div class="math-box">35%</div></div>`}
 ]},
 conv25p:{title:'25% → 1/4',stages:[
  {kind:'html',html:`<div class="math-row"><div class="math-box">25%</div><span class="math-symbol">=</span><div class="math-box">${fraction(25,100,'big')}</div></div>`},
  {kind:'hundred-to-quarter',fill:25,quarters:1,label:'25 dari 100 kotak menjadi 1 kelompok dari 4 kelompok sama besar.'},
  {kind:'html',html:`<div class="math-row"><div class="math-box">25%</div><span class="math-symbol">=</span><div class="math-box">${fraction(1,4,'big')}</div><span class="math-symbol">=</span><div class="math-box">0,25</div></div>`}
 ]},
 conv34:{title:'3/4 → 0,75',stages:exploreMap.fraction34.stages}
};

function toast(msg){const e=document.getElementById('toast');e.textContent=msg;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2200)}
function burstConfetti(){const layer=document.getElementById('confetti');for(let i=0;i<24;i++){const x=document.createElement('i');x.className='confetti-piece';x.style.left=`${Math.random()*100}%`;x.style.animationDelay=`${Math.random()*.3}s`;layer.appendChild(x);setTimeout(()=>x.remove(),1800)}}
function totalProgress(){return Math.round(moduleOrder.reduce((s,k)=>s+(state.modules[k]||0),0)/moduleOrder.length)}
function unlocked(k){const i=moduleOrder.indexOf(k);return i===0||(state.modules[moduleOrder[i-1]]||0)>=100}
function addXP(n){state.xp=Math.max(0,(state.xp||0)+n)}
function persist(sync=true){saveState(state);updateChrome();if(sync)scheduleSync()}
let syncTimer=null;function scheduleSync(){state.sync.pending=true;saveState(state);clearTimeout(syncTimer);syncTimer=setTimeout(doSync,900)}
async function doSync(){const r=await pushProgress(state);if(r?.success){state.sync.pending=false;state.sync.lastSyncedAt=new Date().toISOString();saveState(state);updateSyncText()}}
function updateChrome(){document.getElementById('globalProgressBar').style.width=`${totalProgress()}%`;document.getElementById('globalProgressText').textContent=`${totalProgress()}%`;document.getElementById('xpValue').textContent=state.xp||0;document.getElementById('soundBtn').textContent=state.settings.sound?'🔊':'🔇'}
function updateSyncText(){document.querySelectorAll('[data-sync]').forEach(e=>e.textContent=state.sync.pending?'Menunggu sinkronisasi':'Tersimpan')}

function render(){updateChrome();if(!state.student.id){app.innerHTML=profileView();bindProfile();return}if(route==='home')app.innerHTML=homeView();else if(route==='learn')app.innerHTML=learnView();else if(route==='progress')app.innerHTML=progressView();else if(route==='quiz')app.innerHTML=quizHomeView();else if(route in moduleInfo)app.innerHTML=moduleView(route);else app.innerHTML=homeView();bindCommon()}
function profileView(){return `<section class="card" style="max-width:620px;margin:50px auto"><p class="eyebrow">PROFIL SISWA</p><h1>Siapa yang belajar hari ini?</h1><form id="studentForm"><label>Nama</label><input id="studentName" required maxlength="50"><label>Kelas</label><select id="studentClass">${['VII A','VII B','VII C','VII D','VII E','VII F','VII G'].map(x=>`<option>${x}</option>`).join('')}</select><div class="actions"><button class="btn btn-primary">Mulai Belajar</button></div></form></section>`}
function bindProfile(){document.getElementById('studentForm').onsubmit=e=>{e.preventDefault();const name=document.getElementById('studentName').value.trim(),className=document.getElementById('studentClass').value;state.student={id:`${name.toLowerCase().replace(/\W+/g,'-')}-${Date.now().toString(36)}`,name,className,createdAt:new Date().toISOString()};persist();route='home';render()}}
function homeView(){return `<section class="hero"><div><p class="eyebrow">RATIONAL QUEST</p><h1>Petualangan Bilangan Rasional</h1><p class="lead">Kenali bentuk bilangan rasional, lihat perubahan pecahan, desimal, dan persen melalui animasi pictorial, lalu bandingkan dan urutkan nilainya.</p><div class="actions"><button class="btn btn-primary" data-route="learn">Mulai / Lanjutkan</button><button class="btn btn-secondary" data-route="quiz">Evaluasi</button></div><p class="small" data-sync>${state.sync.pending?'Menunggu sinkronisasi':'Tersimpan'}</p></div><div class="hero-art"><div class="floating-card">${fraction(3,4,'big')}</div><div class="floating-card">0,75</div><div class="floating-card">75%</div></div></section><h2 class="section-title">Peta Perjalanan</h2><section class="grid grid-3">${moduleOrder.map((k,i)=>moduleCard(k,i)).join('')}</section><section class="card" style="margin-top:16px"><h2>🎯 Evaluasi Akhir</h2><p>10 soal acak dari 50 bank soal.</p><button class="btn btn-secondary" data-route="quiz">Buka Evaluasi</button></section>`}
function moduleCard(k,i){const p=state.modules[k]||0,lock=!unlocked(k),m=moduleInfo[k];return `<article class="card module-card ${lock?'locked':''}"><p class="pill">BAGIAN ${i+1}</p><h3>${m.icon} ${m.title}</h3><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div><span class="status">${p>=100?'Selesai ✓':lock?'Terkunci':p>0?`${p}%`:'Siap dimulai'}</span><div class="actions"><button class="btn btn-secondary" data-module="${k}" ${lock?'disabled':''}>${p?'Buka Lagi':'Mulai'}</button></div></article>`}
function learnView(){const next=moduleOrder.find(k=>unlocked(k)&&(state.modules[k]||0)<100)||'comparison';return `<section><p class="eyebrow">BELAJAR</p><h1>Alur Pembelajaran</h1><div class="stepper">${moduleOrder.map((k,i)=>`<div class="step ${(state.modules[k]||0)>=100?'done':k===next?'active':''}">${i+1}. ${moduleInfo[k].title}</div>`).join('')}<div class="step">4. Evaluasi</div></div><div class="grid grid-3" style="margin-top:16px">${moduleOrder.map((k,i)=>moduleCard(k,i)).join('')}</div></section>`}
function progressView(){return `<section><p class="eyebrow">PROGRESS</p><h1>Progress Belajar</h1><div class="card"><div class="progress-list">${moduleOrder.map(k=>`<div class="progress-row"><b>${moduleInfo[k].title}</b><div class="progress-track"><div class="progress-fill" style="width:${state.modules[k]||0}%"></div></div><span>${state.modules[k]||0}%</span></div>`).join('')}</div></div><div class="grid grid-2" style="margin-top:16px"><div class="card"><h2>⭐ ${state.xp} XP</h2><p>Nilai terbaik: <b>${state.quiz.bestScore||0}/100</b></p><p>Percobaan evaluasi: ${state.quiz.attempts||0}</p></div><div class="card"><h2>Badge</h2>${state.badges.length?state.badges.map(b=>`<div class="badge-item">🏅 <b>${b}</b></div>`).join(''):'<p>Belum ada badge.</p>'}</div></div><div class="card" style="margin-top:16px"><h2>Koneksi Apps Script</h2><div id="connectionResult" class="feedback"></div><div class="actions"><button id="testConnection" class="btn btn-secondary">Tes Koneksi</button><button id="syncNow" class="btn btn-secondary">Sinkronkan Sekarang</button><button id="resetProgressBtn" class="btn btn-secondary">Reset Progress</button></div></div></section>`}
function moduleView(k){return k==='concept'?conceptModule():k==='conversion'?conversionModule():comparisonModule()}

function conceptModule(){return `<section class="lesson-layout"><div><p class="eyebrow">BAGIAN 1</p><h1>Kenali Bilangan Rasional</h1><div class="definition-box"><div class="reveal-line" style="--d:1"><b>Pengertian bilangan rasional</b></div><div class="reveal-line" style="--d:2">Bilangan rasional adalah bilangan yang dapat ditulis sebagai pecahan ${fraction('a','b','big')}.</div><div class="reveal-line" style="--d:3">a dan b adalah bilangan bulat, dengan <b>b ≠ 0</b>.</div><div class="reveal-line" style="--d:4">Contoh: ${fraction(3,4,'big')}, ${fraction(-5,4,'big')}, 0,5, 75%, dan 3.</div></div><div class="card" style="margin-top:16px"><h2>Eksplorasi bentuk bilangan</h2><p>Tekan setiap kartu. Ukuran bilangan dan pecahan pada setiap animasi dibuat seragam agar mudah dibaca.</p><div class="explore-cards">${exploreButton('integer3','Bilangan bulat','3')}${exploreButton('decimal05','Desimal','0,5')}${exploreButton('decimal025','Desimal','0,25')}${exploreButton('percent75','Persen','75%')}${exploreButton('fraction34','Pecahan biasa',fraction(3,4,'big'))}${exploreButton('negative125','Desimal negatif','−1,25')}</div><div id="exploreProgress" class="feedback"></div></div><div class="actions"><button class="btn btn-primary" id="completeConcept">Selesaikan Bagian 1</button></div></div><aside class="sticky-panel"><div class="big-math">${fraction(3,4,'big')} = 0,75 = 75%</div></aside></section>`}
function exploreButton(id,label,value){return `<button class="explore-btn" data-explore="${id}"><span>${label}</span><strong>${value}</strong></button>`}
function conversionModule(){return `<section class="lesson-layout"><div><p class="eyebrow">BAGIAN 2</p><h1>Pecahan, Desimal, dan Persen</h1><div class="card soft"><h2>Belajar melalui kartu animasi</h2><p>Seperti Bagian 1, setiap kartu membuka animasi langkah demi langkah. Perhatikan perbedaan antara penyebut 10 dan 100.</p></div><div class="explore-cards" style="margin-top:16px">${convButton('conv06','Penyebut 10','0,6')}${convButton('conv035','Penyebut 100','0,35')}${convButton('conv25p','Persen ke pecahan','25%')}${convButton('conv34','Pecahan ke desimal',fraction(3,4,'big'))}</div><div id="conversionProgress" class="feedback"></div><div class="card" style="margin-top:16px"><h2>Latihan cepat</h2><p>0,25 sama dengan ...</p><div class="option-grid quick-check" data-answer="1/4"><button class="option" data-key="1/4">${fraction(1,4,'big')}</button><button class="option" data-key="2/5">${fraction(2,5,'big')}</button><button class="option" data-key="1/2">${fraction(1,2,'big')}</button><button class="option" data-key="25/10">${fraction(25,10,'big')}</button></div><div class="feedback"></div></div><div class="actions"><button class="btn btn-primary" id="completeConversion">Selesaikan Bagian 2</button></div></div><aside class="sticky-panel"><div class="big-math">0,6 = ${fraction(6,10)} = ${fraction(3,5)}</div></aside></section>`}
function convButton(id,label,value){return `<button class="explore-btn" data-conversion="${id}"><span>${label}</span><strong>${value}</strong></button>`}
function comparisonModule(){return `<section class="lesson-layout"><div><p class="eyebrow">BAGIAN 3</p><h1>Membandingkan & Mengurutkan</h1><div class="card"><h2>Bandingkan dengan gambar penuh</h2><p>Setiap gambar menunjukkan satu bentuk penuh. Bagian berwarna mewakili nilai bilangan.</p><div class="picture-compare">${wholeBar(4,3,`${fraction(3,4,'big')} = 0,75`)}${wholeBar(10,8,'0,8 = 8/10')}</div><div class="hint">0,75 mengisi 75% dari satu penuh, sedangkan 0,8 mengisi 80%. Karena itu ${fraction(3,4)} &lt; 0,8.</div></div><div class="card"><h2>Urutkan dengan pictorial</h2><p>Panjang warna menunjukkan nilai terhadap satu penuh.</p><div class="order-visual">${orderVisual(fraction(1,4,'big'),.25)}${orderVisual(fraction(1,2,'big'),.5)}${orderVisual('0,6',.6)}${orderVisual('0,75',.75)}</div><div class="hint">Dari panjang paling pendek ke paling panjang: ${fraction(1,4)} &lt; ${fraction(1,2)} &lt; 0,6 &lt; 0,75.</div></div><div class="card"><h2>Coba sendiri</h2><p>Manakah yang lebih besar?</p><div class="option-grid quick-check" data-answer="0,6"><button class="option" data-key="1/2">${fraction(1,2,'big')}</button><button class="option" data-key="0,6">0,6</button></div><div class="feedback"></div></div><div class="actions"><button class="btn btn-primary" id="completeComparison">Selesaikan Bagian 3</button></div></div><aside class="sticky-panel"><div class="big-math">Gambar penuh membantu membandingkan nilai tanpa menghafal aturan terlebih dahulu.</div></aside></section>`}
function orderVisual(label,val){return `<div class="order-row"><div class="order-value">${label}</div><div class="mini-full"><div class="mini-fill" style="--fill:${val};width:${val*100}%"></div></div></div>`}

function quizHomeView(){return `<section><p class="eyebrow">EVALUASI AKHIR</p><h1>Uji Pemahaman</h1><div class="card quiz-card"><p><b>10 soal acak</b> akan diambil dari <b>50 bank soal</b>. Urutan soal dan pilihan diacak setiap percobaan.</p><p>Tipe soal: pilihan jawaban, benar/salah, dan memasangkan.</p><div class="actions"><button id="startQuiz" class="btn btn-primary">Mulai Evaluasi</button></div></div></section>`}

function bindCommon(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{route=b.dataset.route;render()});document.querySelectorAll('[data-module]').forEach(b=>b.onclick=()=>{route=b.dataset.module;state.modules[route]=Math.max(state.modules[route]||0,10);persist(false);render()});document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=closeModal);if(route==='concept')bindConcept();if(route==='conversion')bindConversion();if(route==='comparison')bindComparison();if(route==='progress')bindProgress();if(route==='quiz')bindQuizHome();bindQuickChecks()}
function bindConcept(){let seen=new Set(state.__seenExplore||[]);document.querySelectorAll('[data-explore]').forEach(b=>b.onclick=()=>{openExplore(exploreMap,b.dataset.explore);seen.add(b.dataset.explore);state.__seenExplore=[...seen];state.modules.concept=Math.max(state.modules.concept||0,20+seen.size*10);addXP(3);persist(false);const e=document.getElementById('exploreProgress');if(e)e.textContent=`${seen.size} dari 6 eksplorasi sudah dibuka.`});const done=document.getElementById('completeConcept');if(done)done.onclick=()=>completeModule('concept')}
function bindConversion(){let seen=new Set(state.__seenConversion||[]);document.querySelectorAll('[data-conversion]').forEach(b=>b.onclick=()=>{openExplore(conversionCards,b.dataset.conversion);seen.add(b.dataset.conversion);state.__seenConversion=[...seen];state.modules.conversion=Math.max(state.modules.conversion||0,25+seen.size*15);addXP(4);persist(false);const e=document.getElementById('conversionProgress');if(e)e.textContent=`${seen.size} dari 4 kartu animasi sudah dibuka.`});document.getElementById('completeConversion').onclick=()=>completeModule('conversion')}
function bindComparison(){document.getElementById('completeComparison').onclick=()=>completeModule('comparison')}
function bindProgress(){document.getElementById('testConnection').onclick=async()=>{const out=document.getElementById('connectionResult');out.textContent='Menguji koneksi...';const r=await testConnection();out.textContent=r.success?`✓ Terhubung${r.spreadsheetName?' • '+r.spreadsheetName:''}`:`Gagal: ${r.message}`;out.className=`feedback ${r.success?'good':'bad'}`};document.getElementById('syncNow').onclick=async()=>{toast('Mengirim request sinkronisasi...');const r=await pushProgress(state);toast(r.success?'Request sinkronisasi telah dikirim.':'Gagal mengirim request.')};document.getElementById('resetProgressBtn').onclick=()=>{if(confirm('Hapus seluruh progress pada perangkat ini?')){resetState();state=cloneState();route='home';render()}}}
function bindQuickChecks(){document.querySelectorAll('.quick-check').forEach(group=>{const answer=group.dataset.answer,fb=group.nextElementSibling;group.querySelectorAll('.option').forEach(btn=>btn.onclick=()=>{if(group.dataset.done)return;group.dataset.done='1';group.querySelectorAll('.option').forEach(x=>x.disabled=true);const raw=(btn.dataset.key||btn.textContent).trim();const ok=raw===answer;btn.classList.add(ok?'correct':'wrong');fb.textContent=ok?'✓ Benar!':'Belum tepat.';fb.className=`feedback ${ok?'good':'bad'}`;if(ok){addXP(10);persist(false)}})})}
function completeModule(k){if((state.modules[k]||0)<100){addXP(50);if(!state.badges.includes(moduleInfo[k].badge))state.badges.push(moduleInfo[k].badge)}state.modules[k]=100;persist();burstConfetti();toast(`${moduleInfo[k].badge} diperoleh!`);route='learn';render()}

function openExplore(map,id){currentExplore={map,id,step:0};renderExploreModal();modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false')}
function closeModal(){modal.classList.add('hidden');modal.setAttribute('aria-hidden','true');modalBody.innerHTML=''}
function renderExploreModal(){const item=currentExplore.map[currentExplore.id],stage=item.stages[currentExplore.step];modalTitle.innerHTML=fmtText(item.title);let content='';if(stage.kind==='html')content=stage.html;if(stage.kind==='tenths')content=`<div class="visual-stage"><p>${stage.label}</p><div class="tenth-board" id="tenths">${Array.from({length:10},()=>'<div class="tenth"></div>').join('')}</div></div>`;if(stage.kind==='hundred')content=`<div class="visual-stage"><p>${stage.label}</p><div class="grid100" id="grid100">${grid100Html()}</div></div>`;if(stage.kind==='hundred-to-quarter')content=`<div class="visual-stage"><p>${stage.label}</p><div class="grid100" id="grid100">${grid100Html()}</div>${quarterBoard(stage.quarters)}<div id="groupCaption" class="hint" style="opacity:0">100 kotak berubah menjadi 4 kelompok. Setiap kelompok berisi 25 kotak.</div></div>`;modalBody.innerHTML=`<div>${content}</div><div class="actions"><button class="btn btn-secondary" id="prevExplore" ${currentExplore.step===0?'disabled':''}>Sebelumnya</button><button class="btn btn-primary" id="nextExplore">${currentExplore.step===item.stages.length-1?'Selesai':'Langkah Berikutnya'}</button></div>`;document.getElementById('prevExplore').onclick=()=>{currentExplore.step=Math.max(0,currentExplore.step-1);renderExploreModal()};document.getElementById('nextExplore').onclick=()=>{if(currentExplore.step===item.stages.length-1){closeModal();return}currentExplore.step++;renderExploreModal()};if(stage.kind==='tenths')animateTenths(stage.fill);if(stage.kind==='hundred')animateHundred(stage.fill);if(stage.kind==='hundred-to-quarter')animateHundredToQuarter(stage.fill,stage.quarters)}
function animateTenths(fill){const cells=[...modalBody.querySelectorAll('.tenth')];cells.forEach((c,i)=>setTimeout(()=>{if(i<fill)c.classList.add('filled')},i*70))}
function animateHundred(fill){const cells=[...modalBody.querySelectorAll('.cell100')];cells.forEach((c,i)=>setTimeout(()=>{if(i<fill)c.classList.add('q1')},i*12))}
function animateHundredToQuarter(fill,quarters){const cells=[...modalBody.querySelectorAll('.cell100')];cells.forEach((c,i)=>setTimeout(()=>{const group=Math.floor(i/25)+1;if(i<fill)c.classList.add('q'+group);else c.classList.add('dim')},i*7));setTimeout(()=>{const board=modalBody.querySelector('#quarterBoard');if(board)board.classList.add('show');const cap=modalBody.querySelector('#groupCaption');if(cap)cap.style.opacity='1';cells.forEach((c,i)=>{c.style.transform=`scale(${i<fill?'.82':'.72'})`})},900)}

async function getBank(){return await (await fetch('data/questions.json')).json()}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function prepareQuiz(bank){let selected=[];selected.push(...shuffle(bank.filter(q=>q.category==='concept')).slice(0,2));selected.push(...shuffle(bank.filter(q=>q.category==='conversion')).slice(0,3));selected.push(...shuffle(bank.filter(q=>q.category==='comparison')).slice(0,3));selected.push(...shuffle(bank.filter(q=>q.category==='matching')).slice(0,2));return shuffle(selected).map(q=>{const c=JSON.parse(JSON.stringify(q));if(c.options)c.options=shuffle(c.options);if(c.pairs)c.matchOptions=shuffle(c.pairs.map(p=>p.right));return c})}
function bindQuizHome(){const b=document.getElementById('startQuiz');if(b)b.onclick=startQuiz}
async function startQuiz(){quizSession={questions:prepareQuiz(await getBank()),index:0,score:0};renderQuizQuestion()}
function renderQuizQuestion(){const q=quizSession.questions[quizSession.index],p=quizSession.index/quizSession.questions.length*100;app.innerHTML=`<section><p class="eyebrow">EVALUASI AKHIR</p><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div><div class="card quiz-card" style="margin-top:16px"><div class="quiz-head"><b>Soal ${quizSession.index+1} dari ${quizSession.questions.length}</b><span class="small">${q.type==='mcq'?'Pilih jawaban':q.type==='tf'?'Benar / Salah':'Memasangkan'}</span></div><h2>${fmtText(q.prompt)}</h2><div id="quizBody">${renderQuestionBody(q)}</div><div id="quizFeedback" class="feedback"></div><div id="quizHint" class="hint hidden">${fmtText(q.hint||'')}</div><div class="actions"><button id="hintBtn" class="btn btn-secondary">Petunjuk</button><button id="nextBtn" class="btn btn-primary" disabled>Lanjut</button></div></div></section>`;bindQuestion(q)}
function renderQuestionBody(q){
 if(q.type==='mcq')return `<div class="option-grid">${q.options.map(o=>`<button class="option q-option" data-value="${enc(o)}">${fmtText(o)}</button>`).join('')}</div>`;
 if(q.type==='tf')return `<div class="option-grid"><button class="option tf-option" data-value="true">Benar</button><button class="option tf-option" data-value="false">Salah</button></div>`;
 return `<div class="match-grid">${q.pairs.map(p=>`<div class="match-row custom-match-row" data-answer="${enc(p.right)}"><div class="match-left">${fmtText(p.left)}</div><div class="match-choices">${q.matchOptions.map(o=>`<button class="option match-choice" data-value="${enc(o)}">${fmtText(o)}</button>`).join('')}</div></div>`).join('')}</div><div class="actions"><button id="checkMatch" class="btn btn-primary">Periksa Pasangan</button></div>`;
}
function enc(s){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function plain(s){return String(s).replace(/\[\[(-?\d+)\/(\d+)\]\]/g,'$1/$2')}
function bindQuestion(q){
 const next=document.getElementById('nextBtn'),fb=document.getElementById('quizFeedback');
 document.getElementById('hintBtn').onclick=()=>document.getElementById('quizHint').classList.remove('hidden');
 if(q.type==='mcq')document.querySelectorAll('.q-option').forEach(b=>b.onclick=()=>{if(!next.disabled)return;const ok=b.dataset.value===q.answer;document.querySelectorAll('.q-option').forEach(x=>{x.disabled=true;if(x.dataset.value===q.answer)x.classList.add('correct')});if(!ok)b.classList.add('wrong');scoreFeedback(ok,q.answer);next.disabled=false});
 if(q.type==='tf')document.querySelectorAll('.tf-option').forEach(b=>b.onclick=()=>{if(!next.disabled)return;const ok=b.dataset.value===String(q.answer);document.querySelectorAll('.tf-option').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');scoreFeedback(ok,q.answer?'Benar':'Salah');next.disabled=false});
 if(q.type==='match'){
   document.querySelectorAll('.custom-match-row').forEach(row=>{
     row.querySelectorAll('.match-choice').forEach(btn=>btn.onclick=()=>{
       row.querySelectorAll('.match-choice').forEach(x=>x.classList.remove('correct'));
       btn.classList.add('correct');row.dataset.selected=btn.dataset.value;
     });
   });
   document.getElementById('checkMatch').onclick=()=>{
     const rows=[...document.querySelectorAll('.custom-match-row')];
     if(rows.some(r=>!r.dataset.selected)){fb.textContent='Pilih pasangan untuk setiap baris terlebih dahulu.';fb.className='feedback bad';return;}
     const ok=rows.every(r=>r.dataset.selected===r.dataset.answer);
     rows.forEach(r=>r.querySelectorAll('.match-choice').forEach(x=>x.disabled=true));
     scoreFeedback(ok,ok?'Semua pasangan tepat.':'Periksa kembali nilai senilai.');next.disabled=false;
   };
 }
 next.onclick=()=>{quizSession.index++;quizSession.index<quizSession.questions.length?renderQuizQuestion():finishQuiz()};
 function scoreFeedback(ok,ans){fb.innerHTML=ok?'✓ Benar!':`Belum tepat. Jawaban: <b>${fmtText(ans)}</b>`;fb.className=`feedback ${ok?'good':'bad'}`;if(ok){quizSession.score++;addXP(8)}persist(false)}
}
function finishQuiz(){const score=Math.round(quizSession.score/10*100);state.quiz.lastScore=score;state.quiz.bestScore=Math.max(state.quiz.bestScore||0,score);state.quiz.attempts=(state.quiz.attempts||0)+1;if(score>=80&&!state.badges.includes('Rational Master'))state.badges.push('Rational Master');addXP(score>=80?60:30);persist();burstConfetti();app.innerHTML=`<section class="card center" style="max-width:720px;margin:40px auto"><p class="eyebrow">HASIL EVALUASI</p><h1>${score}/100</h1><p>Jawaban benar: ${quizSession.score} dari 10</p><div class="actions" style="justify-content:center"><button id="retry" class="btn btn-primary">Ulangi Evaluasi</button><button id="homeBtn" class="btn btn-secondary">Kembali ke Beranda</button></div></section>`;document.getElementById('retry').onclick=startQuiz;document.getElementById('homeBtn').onclick=()=>{route='home';render()}}

document.getElementById('fullscreenBtn').onclick=()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen?.();else document.exitFullscreen?.()};document.getElementById('soundBtn').onclick=()=>{state.settings.sound=!state.settings.sound;persist(false);updateChrome()};render();
